### ISSUE TITLE
use glance to validate const integrity

### ISSUE THREAD

**Issue by horvathandris** [horvathandris/dime#2]
Currently the lib has a test file that uses simplifile and regexes to test the static integrity of the constants and that:
- they have the same name in lowercase as the currency code
- all currency constants are in the known_currencies list

Could possibly use lpil/glance to parse the source file and test for such integrity.

**Comment by janmarczak** [comment]
![943773263_0340_0340](https://github.com/user-attachments/assets/e9432c1b-d37e-4d57-90cc-f02b67826e3c)

**Comment by horvathandris** [comment]
addressed in 1cfb02cba6cea5862f15e529ba67759f23cd2329
